name: extended_markdown_viewer
description: "A Flutter package that displays markdown text in a flutter widget with support for simple html tags like <u>, <b> and <i>,<li><ol><ul> etc , while also allowing you to expand or collapse the widget"

version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  beautiful_soup_dart: ^0.3.0
  flutter_html: ^2.2.1
  markdown: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
